version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - matrix-flag-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - matrix-flag-network

volumes:
  redis-data:

networks:
  matrix-flag-network:
    driver: bridge 